workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m2
    scripts:
      - name: Get Flutter packages
        script: cd flutter_app_updated && flutter packages pub get
      - name: Build iOS app
        script: cd flutter_app_updated && flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
